### ISSUE TITLE
apple notes missing

### ISSUE THREAD

**Issue by haziqzikry** [mindscapexyz/mindscapexyz_hugo#1]
mana apple notes??? kata daily user??? L

**Comment by mindscapexyz** [comment]
fixed 

<img width="340" alt="image" src="https://github.com/mindscapexyz/mindscapexyz_hugo/assets/58404177/186f0dc9-6b7f-4dfd-b384-6d8b769634af">

thanks for contributing

ranking the note apps:
apple notes
obsidian
*50 layers of shits*
notepad
notion

**Comment by haziqzikry** [comment]
WTF HATE CRIME DETECTED
